Fix typo

diff --git a/packages/pipa-initcpio-hook/android-boot b/packages/pipa-initcpio-hook/android-boot
--- a/packages/pipa-initcpio-hook/android-boot
+++ b/packages/pipa-initcpio-hook/android-boot
@@ -34,8 +34,8 @@ log() {
 }
 
 if [[ "$INITRD_IMAGE" == *"-fallback.img" ]]; then
-    log "Fallback image detected. Stopping"
-    exit 0 
+	log "Fallback image detected. Stopping"
+	exit 0
 fi
 
 CMDLINE=()
@@ -44,14 +44,14 @@ if [ -d "/etc/cmdline.d" ] && find "/etc/cmdline.d" -mindepth 1 | read; then
 		log "Using cmdline file: '$file'"
 		CMDLINE+=("$(<$file)")
 	done
-    CMDLINE="${CMDLINE[@]}"
+	CMDLINE="${CMDLINE[@]}"
 else
-    log "Note: no cmdline files were found" warn
-    log "Reusing current kernel cmdline from /proc/cmdline" warn
-    CMDLINE="$(cat /proc/cmdline)"
+	log "Note: no cmdline files were found" warn
+	log "Reusing current kernel cmdline from /proc/cmdline" warn
+	CMDLINE="$(cat /proc/cmdline)"
 fi
 
-cat "$KERNEL_IMAGE" "$DTB" > "$KERNEL_ZIMAGE"
+cat "$KERNEL_IMAGE" "$DTB" >"$KERNEL_ZIMAGE"
 
 mkbootimg \
 	--header_version 0 \
@@ -68,19 +68,19 @@ mkbootimg \
 
 log "Boot has been built to $ABOOT_IMAGE"
 
-if [ ! -e "/dev/disk/by-partlabel/boot_a" ];then
-    log "Boot partition not found" warn
-    exit 0
+if [ ! -e "/dev/disk/by-partlabel/boot_a" ]; then
+	log "Boot partition not found" warn
+	exit 0
 fi
 
-if ! command -v qbootctl >dev/null 2>&1; then
-    log "Note: qbootctl not found. Cannot find boot slot" warn
-    log "Flash boot image manually" warn
-    exit 0 
+if ! command -v qbootctl >/dev/null 2>&1; then
+	log "Note: qbootctl not found. Cannot find boot slot" warn
+	log "Flash boot image manually" warn
+	exit 0
 fi
 
-slot="$(qbootctl -c 2>/dev/null| awk '{print $3}')"
+slot="$(qbootctl -c 2>/dev/null | awk '{print $3}')"
 log "Detected boot slot: $slot"
 device="/dev/disk/by-partlabel/boot$slot"
 log "Flashing to $device"
-dd if="$ABOOT_IMAGE" of="$device" status=progress > /dev/null 2>&1
+dd if="$ABOOT_IMAGE" of="$device" status=progress >/dev/null 2>&1
